name: Simple Pipeline
on:
  workflow_dispatch:
jobs:
  runpipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.1

    - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2

    - name: Print Hello
        uses: matlab-actions/run-command@v2
        with:
          command: disp('Hello from MATLAB')
